version: '3.8'

services:
  web:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: citationflow-web
    ports:
      - "8080:80"
    networks:
      - citationflow-network
    restart: always

networks:
  citationflow-network:
    driver: bridge
