version: '3.8'

services:
  fastapi:
    build: ./back
    container_name: fastapi-app
    ports:
      - "8000:8000"
      - "5432:5432"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=cf_test
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      - app-network
    volumes:
      - .:/app
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
