version: '3.8'

services:
  backend:
    build:
      context: ./back
    container_name: backend
    ports:
      - "8000:8000"
    restart: always
    environment:
      - PORT=8000
    networks:
      - app-network

  frontend:
    build:
      context: ./front
    container_name: frontend
    ports:
      - "8080:80"
    restart: always
    environment:
      - PORT=3000
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
